<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AndreGas.Web\AndreGas.Web.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4030e4e2-a883-457d-8bea-b091fef5a03a</UserSecretsId>
  </PropertyGroup>

</Project>
